import React, { useState } from 'react';
import { Megaphone, Sparkles, Send } from 'lucide-react';
import { generateAnnouncement } from '../services/geminiService';

export default function Announcements() {
  const [topic, setTopic] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [posts, setPosts] = useState([
    { 
      id: 1, 
      title: 'แจ้งกำหนดการล้างถังพักน้ำ', 
      content: 'ทางหอพักจะทำการล้างถังพักน้ำในวันที่ 15 ก.พ. เวลา 10:00 - 14:00 น. อาจส่งผลให้น้ำไหลอ่อน ขออภัยในความไม่สะดวก', 
      date: '2025-02-01',
      isAiGenerated: true
    }
  ]);

  const handleGenerate = async () => {
    if (!topic) return;
    setIsGenerating(true);
    const content = await generateAnnouncement(topic);
    
    const newPost = {
        id: Date.now(),
        title: `ประกาศ: ${topic}`,
        content: content,
        date: new Date().toISOString().split('T')[0],
        isAiGenerated: true
    };
    
    setPosts([newPost, ...posts]);
    setTopic('');
    setIsGenerating(false);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
       <div className="text-center mb-10">
          <h2 className="text-3xl font-bold text-slate-800">กระดานข่าวสาร</h2>
          <p className="text-slate-500 mt-2">แจ้งเตือนข่าวสารสำคัญถึงผู้เช่าทุกคน</p>
       </div>

       {/* AI Composer */}
       <div className="bg-gradient-to-r from-indigo-600 to-violet-600 rounded-3xl p-1 shadow-xl">
          <div className="bg-white rounded-[22px] p-6">
             <div className="flex items-center gap-2 mb-4 text-indigo-600 font-bold">
                <Sparkles size={20} />
                <h3>AI Announcement Writer</h3>
             </div>
             <div className="flex gap-2">
                <input 
                    type="text" 
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder="พิมพ์หัวข้อข่าวที่ต้องการแจ้ง (เช่น น้ำไม่ไหล, จ่ายค่าไฟ, ปิดปรับปรุง)"
                    className="flex-1 bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                />
                <button 
                    onClick={handleGenerate}
                    disabled={isGenerating || !topic}
                    className="bg-slate-900 text-white px-6 py-3 rounded-xl font-medium hover:bg-slate-800 disabled:opacity-50 transition-all flex items-center gap-2"
                >
                    {isGenerating ? <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <Send size={18} />}
                    <span>สร้างประกาศ</span>
                </button>
             </div>
          </div>
       </div>

       {/* Timeline */}
       <div className="space-y-6 relative before:absolute before:inset-y-0 before:left-8 before:w-0.5 before:bg-slate-200">
          {posts.map((post) => (
             <div key={post.id} className="relative pl-20 animate-in slide-in-from-bottom-4 fade-in duration-500">
                <div className="absolute left-5 top-0 w-6 h-6 bg-indigo-600 rounded-full border-4 border-white shadow-md flex items-center justify-center z-10">
                </div>
                <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-all group">
                    <div className="flex justify-between items-start mb-3">
                        <h4 className="text-xl font-bold text-slate-800 group-hover:text-indigo-600 transition-colors">{post.title}</h4>
                        <span className="text-xs text-slate-400 font-medium">{post.date}</span>
                    </div>
                    <p className="text-slate-600 leading-relaxed whitespace-pre-line">{post.content}</p>
                    {post.isAiGenerated && (
                        <div className="mt-4 flex items-center gap-1 text-[10px] text-indigo-400 uppercase font-bold tracking-wider opacity-60">
                            <Sparkles size={10} /> Generated by NexDorm AI
                        </div>
                    )}
                </div>
             </div>
          ))}
       </div>
    </div>
  );
}
